// !!! WARNING: This is a GENERATED Code..Please do NOT Edit !!!
#pragma once

#include <iostream>

#include <list>
#include <map>

// Dictionary of meta data eg IPMI Propertyname,FRU Section
// for a specific DBUS property.
using MetaDataMap = std::map<std::string,std::string>;

// Dictionary of Dbus property and the associated metaData.
using PropertiesMap = std::map<std::string,MetaDataMap>;

// Dictionary of Interface and the Properties.
using InterfacePropertiesMap = std::map<std::string,PropertiesMap>;

// Dictionary of object and the interfaces.
using ObjectInterfaceMap = std::map<std::string,InterfacePropertiesMap>;

// Dictionary of fru and the objects.
using FruObjectMap = std::map<int,ObjectInterfaceMap>;


const FruObjectMap  frus = {
   {1,{

         {"/system",{
             {"xyz.openbmc_project.Inventory.Revision",{
                 {"Version",{
                     {"FRUSection","PRODUCT"},
                     {"VpdPropertyName","Version"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","True"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Decorator.Asset",{
                 {"PartNumber",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Part Number"},
                 }},
                 {"SerialNumber",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Serial Number"},
                 }},
                 {"BuildDate",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Mfg Date"},
                 }},
                 {"Manufacturer",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Manufacturer"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
   }},
   {2,{

         {"/system/chassis",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","True"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Decorator.Asset",{
                 {"PartNumber",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Part Number"},
                 }},
                 {"SerialNumber",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Serial Number"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
   }},
   {3,{

         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq1/ex2/core4",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq1/ex2/core5",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq2/ex4/core9",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq2/ex4/core8",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq3/ex7/core15",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq3/ex7/core14",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/system/chassis/motherboard/cpu1",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","True"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Decorator.Asset",{
                 {"PartNumber",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Part Number"},
                 }},
                 {"SerialNumber",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Serial Number"},
                 }},
                 {"BuildDate",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Mfg Date"},
                 }},
                 {"Manufacturer",{
                     {"FRUSection","BOARD"},
                     {"VpdPropertyName","Manufacturer"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq0/ex0/core1",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq0/ex0/core0",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq3/ex6/core12",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq3/ex6/core13",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq5/ex10/core21",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq5/ex10/core20",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq0/ex1/core2",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq0/ex1/core3",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq4/ex9/core18",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq4/ex9/core19",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq5/ex11/core22",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq4/ex8/core17",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq4/ex8/core16",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq5/ex11/core23",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq2/ex5/core10",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq1/ex3/core7",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq1/ex3/core6",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
         {"/sys-0/node-0/motherboard-0/proc_socket-1/module-0/p9_proc_m/eq2/ex5/core11",{
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","False"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
   }},
   {4,{

         {"/system/chassis/motherboard/dimm9",{
             {"xyz.openbmc_project.Inventory.Revision",{
                 {"Version",{
                     {"FRUSection","PRODUCT"},
                     {"VpdPropertyName","Version"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Decorator.Replaceable",{
                 {"FieldReplaceable",{
                     {"Value","True"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Decorator.Asset",{
                 {"PartNumber",{
                     {"FRUSection","PRODUCT"},
                     {"VpdPropertyName","Part Number"},
                 }},
                 {"SerialNumber",{
                     {"FRUSection","PRODUCT"},
                     {"VpdPropertyName","Serial Number"},
                 }},
                 {"BuildDate",{
                     {"FRUSection","PRODUCT"},
                     {"VpdPropertyName","Mfg Date"},
                 }},
                 {"Manufacturer",{
                     {"FRUSection","PRODUCT"},
                     {"VpdPropertyName","Manufacturer"},
                 }},
             }},
             {"xyz.openbmc_project.Inventory.Item",{
                 {"Present",{
                     {"Value","True"},
                 }},
             }},
        }},
   }},
};
