/* !!!! WARNING: This is a GENERATED Code..Please do NOT Edit !!!! */

#include "inventory-gen.hpp"

fruObjectDict fruList = {
{
"1",{
{
"/system/chassis/motherboard/cpu/core3",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core2",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core1",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core0",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core7",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core6",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core5",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core4",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core9",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core8",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core11",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu/core10",{
{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis/motherboard/cpu",{
{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Serial Number"},}
},{
"BuildDate",{
{
"Section","BOARD"},{
"VpdPropertyName","Mfg. Date"},}
},{
"Manufacturer",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"2",{
{
"/system/chassis/motherboard/membuf",{
{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Serial Number"},}
},{
"BuildDate",{
{
"Section","BOARD"},}
},{
"Manufacturer",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},{
"/system/chassis",{
{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Serial Number"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"3",{
{
"/system/chassis/motherboard/dimm0",{
{
"xyz.openbmc_project.Inventory.Revision",{
{
"Version",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Product Version"},}
},}
},{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Serial Number"},}
},{
"Manufacturer",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"4",{
{
"/system/chassis/motherboard/dimm1",{
{
"xyz.openbmc_project.Inventory.Revision",{
{
"Version",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Product Version"},}
},}
},{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Serial Number"},}
},{
"Manufacturer",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"5",{
{
"/system/chassis/motherboard/dimm2",{
{
"xyz.openbmc_project.Inventory.Revision",{
{
"Version",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Product Version"},}
},}
},{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Serial Number"},}
},{
"Manufacturer",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"6",{
{
"/system/chassis/motherboard/dimm3",{
{
"xyz.openbmc_project.Inventory.Revision",{
{
"Version",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Product Version"},}
},}
},{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Serial Number"},}
},{
"Manufacturer",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"14",{
{
"/system/chassis/motherboard",{
{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Serial Number"},}
},{
"BuildDate",{
{
"Section","BOARD"},{
"VpdPropertyName","Mfg. Date"},}
},{
"Manufacturer",{
{
"Section","BOARD"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},{
"15",{
{
"/system",{
{
"xyz.openbmc_project.Inventory.Revision",{
{
"Version",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Product Version"},}
},}
},{
"xyz.openbmc_project.Inventory.Asset",{
{
"PartNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Part Number"},}
},{
"SerialNumber",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Serial Number"},}
},{
"Manufacturer",{
{
"Section","PRODUCT"},{
"VpdPropertyName","Board Manufacturer"},}
},}
},{
"xyz.openbmc_project.Inventory.Replaceable",{
{
"FieldReplaceable",{
{
"DefaultValue","False"},}
},}
},{
"xyz.openbmc_project.Inventory.Item",{
{
"Present",{
{
"DefaultValue","True"},}
},}
},}
},}
},}
;

